live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[env]
TERM = "alacritty"

[font]
size = 19

[font.normal]
family = "monospace"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
opacity = 0.85
